"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { AppHeader } from "@/components/app-header";
import { RequireAuth } from "@/components/require-auth";
import { ApiError } from "@/lib/api-client";
import { useAuth } from "@/lib/auth-context";

type TaskStatus = "todo" | "in_progress" | "done";

interface Task {
  id: string;
  bookingId: string | null;
  title: string;
  category: string | null;
  dueDate: string | null;
  status: TaskStatus;
  assignee: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
}

interface Progress {
  total: number;
  done: number;
  percentComplete: number;
}

interface ListResponse {
  tasks: Task[];
  progress: Progress;
}

interface BudgetCategory {
  category: string;
  committed: number;
  paid: number;
}

interface BudgetSummary {
  budgetTotal: number | null;
  totalCommitted: number;
  totalPaid: number;
  remaining: number | null;
  byCategory: BudgetCategory[];
}

const STATUS_LABELS: Record<TaskStatus, string> = {
  todo: "To do",
  in_progress: "In progress",
  done: "Done",
};

export default function ChecklistPage() {
  return (
    <RequireAuth>
      <AppHeader />
      <ChecklistContent />
    </RequireAuth>
  );
}

function ChecklistContent() {
  const { user, authFetch } = useAuth();
  const [tasks, setTasks] = useState<Task[] | null>(null);
  const [progress, setProgress] = useState<Progress | null>(null);
  const [budget, setBudget] = useState<BudgetSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  async function loadList() {
    try {
      const data = await authFetch<ListResponse>("/checklist");
      setTasks(data.tasks);
      setProgress(data.progress);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to load checklist");
    }
  }

  async function loadBudget() {
    try {
      setBudget(await authFetch<BudgetSummary>("/checklist/budget"));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to load budget");
    }
  }

  useEffect(() => {
    loadList();
    loadBudget();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const data = await authFetch<ListResponse & { created: number }>("/checklist/generate", {
        method: "POST",
      });
      setTasks(data.tasks);
      setProgress(data.progress);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to generate checklist");
    } finally {
      setGenerating(false);
    }
  }

  if (!user) return null;
  if (user.role !== "inquirer") {
    return (
      <main className="mx-auto max-w-2xl px-4 py-16">
        <p className="text-sm text-gray-600">This page is only available to couples planning a wedding.</p>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-2xl px-4 py-10">
      <h1 className="mb-6 text-2xl font-bold">Checklist</h1>

      {error && <p className="mb-4 text-sm text-red-600">{error}</p>}

      {progress && (
        <div className="mb-6">
          <div className="mb-1 flex items-center justify-between text-sm text-gray-600">
            <span>
              {progress.done} of {progress.total} tasks done
            </span>
            <span>{progress.percentComplete}%</span>
          </div>
          <div className="h-2 rounded-full bg-gray-100">
            <div
              className="h-2 rounded-full bg-gray-900"
              style={{ width: `${progress.percentComplete}%` }}
            />
          </div>
        </div>
      )}

      <button
        onClick={handleGenerate}
        disabled={generating}
        className="mb-8 rounded-md border border-gray-300 px-4 py-2 text-sm font-medium hover:bg-gray-100 disabled:opacity-50"
      >
        {generating ? "Generating..." : "Generate / refresh timeline"}
      </button>

      <BudgetSection budget={budget} />

      <AddTaskForm onAdded={loadList} />

      {tasks === null && !error && <p className="text-sm text-gray-600">Loading...</p>}
      {tasks?.length === 0 && (
        <p className="text-sm text-gray-600">
          No tasks yet — set your wedding date on your profile, then generate a timeline.
        </p>
      )}

      <div className="flex flex-col gap-2">
        {tasks?.map((task) => (
          <TaskRow key={task.id} task={task} onChanged={loadList} />
        ))}
      </div>
    </main>
  );
}

function BudgetSection({ budget }: { budget: BudgetSummary | null }) {
  if (!budget) return null;
  return (
    <div className="mb-8 rounded-lg border border-gray-200 p-4">
      <h2 className="mb-2 text-sm font-semibold">Budget</h2>
      <div className="flex flex-wrap gap-x-6 gap-y-1 text-sm text-gray-700">
        <span>Budget: {budget.budgetTotal !== null ? `$${budget.budgetTotal.toLocaleString()}` : "not set"}</span>
        <span>Committed: ${budget.totalCommitted.toLocaleString()}</span>
        <span>Paid: ${budget.totalPaid.toLocaleString()}</span>
        {budget.remaining !== null && <span>Remaining: ${budget.remaining.toLocaleString()}</span>}
      </div>
      {budget.byCategory.length > 0 && (
        <ul className="mt-3 flex flex-col gap-1 text-xs text-gray-600">
          {budget.byCategory.map((c) => (
            <li key={c.category} className="flex justify-between">
              <span>{c.category}</span>
              <span>
                ${c.paid.toLocaleString()} paid / ${c.committed.toLocaleString()} committed
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function AddTaskForm({ onAdded }: { onAdded: () => Promise<void> }) {
  const { authFetch } = useAuth();
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [assignee, setAssignee] = useState("");
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);
    try {
      await authFetch("/checklist", {
        method: "POST",
        body: {
          title,
          category: category || undefined,
          dueDate: dueDate || undefined,
          assignee: assignee || undefined,
        },
      });
      setTitle("");
      setCategory("");
      setDueDate("");
      setAssignee("");
      await onAdded();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to add task");
    }
  }

  return (
    <form onSubmit={handleSubmit} className="mb-6 flex flex-wrap items-end gap-2">
      <input
        required
        placeholder="New task"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="min-w-[160px] flex-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
      />
      <input
        placeholder="Category"
        value={category}
        onChange={(e) => setCategory(e.target.value)}
        className="w-28 rounded-md border border-gray-300 px-3 py-2 text-sm"
      />
      <input
        type="date"
        value={dueDate}
        onChange={(e) => setDueDate(e.target.value)}
        className="rounded-md border border-gray-300 px-3 py-2 text-sm"
      />
      <input
        placeholder="Assignee"
        value={assignee}
        onChange={(e) => setAssignee(e.target.value)}
        className="w-28 rounded-md border border-gray-300 px-3 py-2 text-sm"
      />
      <button type="submit" className="rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700">
        Add
      </button>
      {error && <p className="w-full text-sm text-red-600">{error}</p>}
    </form>
  );
}

function TaskRow({ task, onChanged }: { task: Task; onChanged: () => Promise<void> }) {
  const { authFetch } = useAuth();
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function saveFull(fields: Partial<Pick<Task, "title" | "category" | "dueDate" | "status" | "assignee">>) {
    setError(null);
    try {
      await authFetch(`/checklist/${task.id}`, {
        method: "PUT",
        body: {
          title: task.title,
          category: task.category ?? undefined,
          dueDate: task.dueDate ?? undefined,
          status: task.status,
          assignee: task.assignee ?? undefined,
          ...fields,
        },
      });
      await onChanged();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to update task");
    }
  }

  async function handleDelete() {
    if (!confirm(`Delete "${task.title}"?`)) return;
    setError(null);
    try {
      await authFetch(`/checklist/${task.id}`, { method: "DELETE" });
      await onChanged();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to delete task");
    }
  }

  if (editing) {
    return (
      <EditTaskForm
        task={task}
        onCancel={() => setEditing(false)}
        onSaved={async (fields) => {
          await saveFull(fields);
          setEditing(false);
        }}
      />
    );
  }

  return (
    <div className="flex items-center gap-3 rounded-lg border border-gray-200 p-3">
      <select
        value={task.status}
        onChange={(e) => saveFull({ status: e.target.value as TaskStatus })}
        className={
          "rounded-md border px-2 py-1 text-xs font-medium " +
          (task.status === "done"
            ? "border-green-300 bg-green-50 text-green-800"
            : task.status === "in_progress"
              ? "border-amber-300 bg-amber-50 text-amber-800"
              : "border-gray-300 bg-gray-50 text-gray-700")
        }
      >
        <option value="todo">{STATUS_LABELS.todo}</option>
        <option value="in_progress">{STATUS_LABELS.in_progress}</option>
        <option value="done">{STATUS_LABELS.done}</option>
      </select>
      <div className="flex-1">
        <p className={task.status === "done" ? "text-sm text-gray-400 line-through" : "text-sm"}>
          {task.title}
        </p>
        <p className="text-xs text-gray-500">
          {[task.category, task.dueDate, task.assignee].filter(Boolean).join(" · ")}
        </p>
        {error && <p className="text-xs text-red-600">{error}</p>}
      </div>
      <div className="flex gap-2 text-xs">
        <button onClick={() => setEditing(true)} className="text-gray-700 underline">
          Edit
        </button>
        <button onClick={handleDelete} className="text-red-600 underline">
          Delete
        </button>
      </div>
    </div>
  );
}

function EditTaskForm({
  task,
  onSaved,
  onCancel,
}: {
  task: Task;
  onSaved: (fields: { title: string; category?: string; dueDate?: string; assignee?: string }) => Promise<void>;
  onCancel: () => void;
}) {
  const [title, setTitle] = useState(task.title);
  const [category, setCategory] = useState(task.category ?? "");
  const [dueDate, setDueDate] = useState(task.dueDate ?? "");
  const [assignee, setAssignee] = useState(task.assignee ?? "");
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    await onSaved({
      title,
      category: category || undefined,
      dueDate: dueDate || undefined,
      assignee: assignee || undefined,
    });
    setSubmitting(false);
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-wrap items-end gap-2 rounded-lg border border-gray-200 p-3">
      <input
        required
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="min-w-[160px] flex-1 rounded-md border border-gray-300 px-2 py-1.5 text-sm"
      />
      <input
        placeholder="Category"
        value={category}
        onChange={(e) => setCategory(e.target.value)}
        className="w-28 rounded-md border border-gray-300 px-2 py-1.5 text-sm"
      />
      <input
        type="date"
        value={dueDate}
        onChange={(e) => setDueDate(e.target.value)}
        className="rounded-md border border-gray-300 px-2 py-1.5 text-sm"
      />
      <input
        placeholder="Assignee"
        value={assignee}
        onChange={(e) => setAssignee(e.target.value)}
        className="w-28 rounded-md border border-gray-300 px-2 py-1.5 text-sm"
      />
      <button
        type="submit"
        disabled={submitting}
        className="rounded-md bg-gray-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-gray-700 disabled:opacity-50"
      >
        Save
      </button>
      <button type="button" onClick={onCancel} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">
        Cancel
      </button>
    </form>
  );
}
