// Shared domain types — kept in sync with db/migrations/*.sql.
// Claude Code: regenerate/extend these as the schema evolves; treat the
// SQL migrations as the source of truth if the two ever drift.

export type UserRole = "inquirer" | "vendor" | "admin";

export interface User {
  id: string;
  email: string;
  role: UserRole;
  mfaEnabled: boolean;
  emailVerifiedAt: string | null;
  isActive: boolean;
  createdAt: string;
}

export interface InquirerProfile {
  userId: string;
  displayName: string;
  weddingDate: string | null;
  venueLocation: string | null;
  guestCount: number | null;
  budgetTotal: number | null;
  styleTags: string[];
}

export type VerificationStatus = "unverified" | "pending" | "verified" | "rejected";

export interface VendorProfile {
  userId: string;
  businessName: string;
  categories: string[];
  serviceArea: string | null;
  bio: string | null;
  verificationStatus: VerificationStatus;
  avgRating: number;
  reviewCount: number;
}

export type PricingType = "flat" | "hourly" | "per_guest" | "tiered" | "custom_quote";

export interface VendorPackage {
  id: string;
  vendorId: string;
  name: string;
  category: string;
  description: string | null;
  pricingType: PricingType;
  basePrice: number | null;
  depositPct: number;
  cancellationPolicy: string | null;
  isActive: boolean;
}

export type AvailabilityStatus = "open" | "tentative_hold" | "booked" | "blocked";

export interface AvailabilitySlot {
  id: string;
  vendorId: string;
  date: string;
  status: AvailabilityStatus;
  holdExpiresAt: string | null;
  bookingId: string | null;
}

export type InquiryStatus = "open" | "quoted" | "hold" | "contracted" | "declined" | "closed";

export interface Inquiry {
  id: string;
  inquirerId: string;
  vendorId: string;
  category: string;
  eventDate: string | null;
  status: InquiryStatus;
  createdAt: string;
}

export type MessageChannel = "app" | "email" | "system";

export interface Message {
  id: string;
  conversationId: string;
  senderId: string;
  body: string;
  sentVia: MessageChannel;
  emailMessageId: string | null;
  readAt: string | null;
  flagged: boolean;
  createdAt: string;
}

export type QuoteStatus = "draft" | "sent" | "accepted" | "declined" | "expired";

export interface QuoteLineItem {
  label: string;
  amount: number;
}

export interface Quote {
  id: string;
  inquiryId: string;
  lineItems: QuoteLineItem[];
  totalAmount: number;
  depositAmount: number;
  validUntil: string | null;
  status: QuoteStatus;
}

export type BookingStatus =
  | "hold"
  | "contracted"
  | "deposit_paid"
  | "confirmed"
  | "completed"
  | "cancelled";

export interface Booking {
  id: string;
  quoteId: string;
  inquirerId: string;
  vendorId: string;
  eventDate: string;
  status: BookingStatus;
  contractDocUrl: string | null;
  totalAmount: number;
  depositPaidAt: string | null;
  balanceDueAt: string | null;
}

export type PaymentType = "deposit" | "milestone" | "final" | "refund";
export type PaymentStatus = "pending" | "succeeded" | "failed" | "refunded";

export interface Payment {
  id: string;
  bookingId: string;
  amount: number;
  type: PaymentType;
  status: PaymentStatus;
  stripeRef: string | null;
}

export type TaskStatus = "todo" | "in_progress" | "done";

export interface ChecklistTask {
  id: string;
  inquirerId: string;
  bookingId: string | null;
  title: string;
  category: string | null;
  dueDate: string | null;
  status: TaskStatus;
  assignee: string | null;
  isAutoGenerated: boolean;
}

export interface Review {
  id: string;
  bookingId: string;
  rating: 1 | 2 | 3 | 4 | 5;
  body: string | null;
  vendorResponse: string | null;
}
