import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { CHECKLIST_TEMPLATE } from "./checklist-template";
import { ChecklistRepository, ChecklistTaskRow } from "./checklist.repository";
import { CreateTaskDto } from "./dto/create-task.dto";
import { UpdateTaskDto } from "./dto/update-task.dto";

@Injectable()
export class ChecklistService {
  constructor(private readonly repo: ChecklistRepository) {}

  async generate(inquirerId: string) {
    const weddingDate = await this.repo.findWeddingDate(inquirerId);
    if (!weddingDate) {
      throw new BadRequestException("Set your wedding date before generating a checklist");
    }
    const created = await this.repo.generateFromTemplate(inquirerId, weddingDate, CHECKLIST_TEMPLATE);
    await this.syncBookedCategories(inquirerId);
    const { tasks, progress } = await this.list(inquirerId);
    return { created, tasks, progress };
  }

  // Marks any template task whose category matches a category the inquirer
  // already has a live booking for as done — the "booking a vendor
  // auto-creates/updates related tasks" behavior from spec 3.5, run as an
  // explicit sync rather than a reactive hook (checklist has no dependency
  // on the bookings module beyond this read-only query).
  async syncBookedCategories(inquirerId: string): Promise<void> {
    const categories = await this.repo.findBookedCategories(inquirerId);
    await this.repo.markDoneByCategories(inquirerId, categories);
  }

  async list(inquirerId: string) {
    const rows = await this.repo.listForInquirer(inquirerId);
    const tasks = rows.map((r) => this.toDto(r));
    const total = tasks.length;
    const done = tasks.filter((t) => t.status === "done").length;
    return {
      tasks,
      progress: {
        total,
        done,
        percentComplete: total === 0 ? 0 : Math.round((done / total) * 100),
      },
    };
  }

  async getBudgetSummary(inquirerId: string) {
    const [budgetTotalRaw, committedRows, paidRows] = await Promise.all([
      this.repo.findBudgetTotal(inquirerId),
      this.repo.findCommittedByCategory(inquirerId),
      this.repo.findPaidByCategory(inquirerId),
    ]);

    const byCategory = new Map<string, { category: string; committed: number; paid: number }>();
    for (const row of committedRows) {
      byCategory.set(row.category, { category: row.category, committed: Number(row.committed), paid: 0 });
    }
    for (const row of paidRows) {
      const existing = byCategory.get(row.category);
      if (existing) {
        existing.paid = Number(row.paid);
      } else {
        byCategory.set(row.category, { category: row.category, committed: 0, paid: Number(row.paid) });
      }
    }

    const categories = [...byCategory.values()].sort((a, b) => a.category.localeCompare(b.category));
    const totalCommitted = categories.reduce((sum, c) => sum + c.committed, 0);
    const totalPaid = categories.reduce((sum, c) => sum + c.paid, 0);
    const budgetTotal = budgetTotalRaw != null ? Number(budgetTotalRaw) : null;

    return {
      budgetTotal,
      totalCommitted,
      totalPaid,
      remaining: budgetTotal !== null ? budgetTotal - totalPaid : null,
      byCategory: categories,
    };
  }

  async create(inquirerId: string, dto: CreateTaskDto) {
    const row = await this.repo.create(inquirerId, dto);
    return this.toDto(row);
  }

  async update(inquirerId: string, taskId: string, dto: UpdateTaskDto) {
    const updated = await this.repo.update(taskId, inquirerId, dto);
    if (!updated) {
      throw new NotFoundException("Task not found");
    }
    return this.toDto(updated);
  }

  async delete(inquirerId: string, taskId: string): Promise<void> {
    const deleted = await this.repo.delete(taskId, inquirerId);
    if (!deleted) {
      throw new NotFoundException("Task not found");
    }
  }

  private toDto(row: ChecklistTaskRow) {
    return {
      id: row.id,
      bookingId: row.booking_id,
      title: row.title,
      category: row.category,
      dueDate: row.due_date,
      status: row.status,
      assignee: row.assignee,
      isAutoGenerated: row.is_auto_generated,
      createdAt: row.created_at,
    };
  }
}
